baseURL = 'https://onbreakpoint.com'
locale = 'en-us'
title = "on breakpoint"

[params]
hideMadeWithLine = true

[permalinks]
writing = "/:slug/"
notes = "/:slug/"

[markup.highlight]
noClasses = true
style = "none"
